fix: fixed NoSuchMethodError: 'void org.springframework.web.method.ControllerAdviceBean' due to incompatible version of springdoc-openapi-starter-webmvc-ui